config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  resources :friends
  #get 'home/index'
  get 'home/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #root 'home#index'
  root 'friends#index'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    # return unless user.present?
    # can :read, :all
    return unless user.admin?
    can :read, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends
  ROLES = %w{super_admin admin manager editior collaborator}

  ROLES.each do |role_name|
    define_method "#{role_name}?"do
      role == role_name
    end
  end
  # def jwt_payload
  #   super
  # end

  # def super_admin?
  #   role == 'super_admin'
  # end

  # def admin?
  #   role == 'admin'
  # end

  # def manager?
  #   role == 'manager'
  # end

  # def editior?
  #   role == 'editior'
  # end

  # def collaborator?
  #   role == 'collaborator'
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  #load_and_authorize_resource
  before_action :set_friend, only: %i[ show edit update destroy ]
  #before_action :authenticate_user!, expect: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /friends or /friends.json
  def index
    # @friends = current_user.friends
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    # @friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    # @friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
       format.html { redirect_to friends_url(@friend), notice: "Friend was successfully destroyed." }
       format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Authorized to Edit this Friend" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
    @about_me = "My Name is Nikhlesh......"
    @answer = 2 + 2
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>

  <div class="mb-3">
    <%= form.text_field :last_name, class:"form-control",placeholder:"Last Name" %>
  </div>

  <div class="mb-3">
    <%= form.text_field :email, class:"form-control",placeholder:"Email" %>
  </div>

  <div class="mb-3">
    <%= form.text_field :phone, class:"form-control",placeholder:"Mobile Number" %>
  </div>
  <div class="mb-3">
    <%= form.text_field :twitter, class:"form-control",placeholder:"Twitter" %>
  </div>
  <div class="mb-3">
    <%= form.number_field :user_id,id: :friend_user_id, class:"form-control", value: current_user.id,type: :hidden %>
  </div>
  <div class="actions">
    <%= form.submit class:"btn btn-secondary" %>
  </div>

  
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  
  <td>
    <%= link_to friend.first_name + ' ' + friend.last_name, friend %>
  </td>

  <td>
    <%= friend.email %>
  </td>

  <td>
    <%= friend.phone %>
  </td>

  <td>
    <%= friend.twitter %>
  </td>

  <!-- <td>
    <%= friend.user_id %>
  </td> -->

</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1><br>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show", @friend, class:"btn btn-secondary" %> 
  <%= link_to "Back", friends_path, class:"btn btn-dark" %> <br></br>
  <!-- <%= button_to 'Delete', @friend, method: :delete, data: { turbo_confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %> -->
</div>

app/views/friends/index.html.erb
<% if user_signed_in? %>
  <p id="notice"><%= notice %></p>
  <h1>Friends List</h1>
  <table class="table table-striped table-bordered table-hover">
      <thead class="table-dark">
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Phone</th>
          <th>Twitter</th>
          <!-- <th>User Id</th> -->
          <th> </th>
        </tr>
      </thead>
      <tbody>
        <div id="friends">
          <% @friends.each do |friend| %>
            <% if friend.user == current_user %>
              <tr>
                <%= render friend %>
                <td><%= button_to 'Delete', friend_path(friend), method: :delete, data: { turbo_confirm: 'Are you sure?' }, 
              class: "btn btn-outline-danger btn-sm" %></td>
              </tr>
              <% end %>
            <% end %>
        </div>
      </tbody>
  </table>

  <%= link_to "New friend", new_friend_path, class:"btn btn-secondary" %>
<% else %>
  <h2>Hello World</h2>
<% end %>

app/views/friends/new.html.erb
<h1>New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back", friends_path, class:"btn btn-dark" %>
</div>

app/views/friends/show.html.erb
<p style="color: green"><%= notice %></p>

<!-- <%= render @friend %> -->
<div class="col-md-5 d-flex justify-content-center">
  <div class="h-100 p-5 text-bg-dark rounded-3">
    <p>
      <strong>First name:</strong>
      <%= @friend.first_name %>
    </p>
    <p>
      <strong>Last name:</strong>
      <%= @friend.last_name %>
    </p>
    <p>
      <strong>Email:</strong>
      <%= @friend.email %>
    </p>
    <p>
      <strong>Phone Number:</strong>
      <%= @friend.phone %>
    </p>
    <p>
      <strong>Twitter:</strong>
      <%= @friend.twitter %>
    </p>
    <div>
      <%= link_to "Edit", edit_friend_path(@friend), class:"btn btn-secondary" %> |
      <%= link_to "Back", friends_path, class:"btn btn-outline-light" %> 
    </div>
  </div>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  	<%= link_to 'Friend App', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
         <%= link_to "About Us", home_about_path, class:"nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
           <%= link_to "Add Friend", new_friend_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, turbo_method: :delete, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
           <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
           <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
          </li>
        <% end %>
        
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us....</h1>

<p>
	<%= @about_me %><br/>
	2 + 2 = <%= @answer %>
</p>

app/views/home/index.html.erb
<h1>Hello World !</h1>

app/views/layouts/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friends</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'home/header' %>
    <div class="container">
    <br/>
    <% if notice %>
      <%= render 'layouts/alert' %>
    <% end %>
       <%= yield %>
    </div>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>